Repository glotzerlab/signac, pull requests merged in 2019-12, with the labels that each got.

#252 Use Config class to write config during init_project.
  changelog.txt
  signac/contrib/project.py
  tests/test_project.py
Labels: bug

#256 Small documentation fixes in preparation for v1.3.
  doc/conf.py
  doc/support.rst
  signac/contrib/errors.py
  signac/contrib/project.py
Labels: documentation

#258 Add support for Python 3.8
  .circleci/config.yml
  changelog.txt
  setup.py
  tests/test_project.py
Labels: enhancement

#253 Add schema version
  changelog.txt
  requirements.txt
  setup.py
  signac/__main__.py
  signac/common/validate.py
  signac/contrib/errors.py
  signac/contrib/migration/__init__.py
  signac/contrib/migration/v0_to_v1.py
  signac/contrib/project.py
  signac/version.py
  tests/test_project.py
Labels: enhancement

#247 adding signac diff functionality
  changelog.txt
  contributors.yaml
  doc/cli-help.txt
  signac/__init__.py
  signac/__main__.py
  signac/diff.py
  tests/test_diff.py
Labels: enhancement

#260 Update logo images and documentation style.
  README.md
  doc/conf.py
  doc/images/favicon.ico
  doc/images/logo.png
  doc/images/palette-header.png
Labels: documentation

#261 Add missing CSS files.
  .gitignore
  doc/_static/css/signac-theme.css
Labels: documentation
