Repository glotzerlab/signac, pull requests merged in 2019-02, with the labels that each got.

#118 Add get_job function
  changelog.txt
  signac/__init__.py
  signac/__main__.py
  signac/contrib/__init__.py
  signac/contrib/job.py
  signac/contrib/project.py
  tests/test_project.py
Labels: Job

#125 Resolve issue #120 by allowing job methods to be chained.
  changelog.txt
  signac/contrib/job.py
  tests/test_job.py
Labels: Job, enhancement

#136 Fix pandas Project representation tests.
  tests/test_project.py
Labels: Project, bug

#135 Remove index from Project.find_jobs()
  changelog.txt
  signac/contrib/project.py
Labels: API, Project

#147 Fix/rapidjson encoder issue
  .circleci/config.yml
  signac/common/host.py
  signac/contrib/collection.py
  signac/contrib/filterparse.py
  signac/contrib/hashing.py
  signac/contrib/import_export.py
  signac/contrib/indexing.py
  signac/contrib/job.py
  signac/contrib/project.py
  signac/core/json.py
  signac/core/jsondict.py
Labels: bug

#149 Properly handle Job.move() error conditions.
  signac/contrib/job.py
  tests/test_job.py
Labels: bug

#155 Update changelog for version 1.0.0.
  changelog.txt
Labels: documentation

#156 Fix/schema subset
  changelog.txt
  signac/contrib/schema.py
  tests/test_project.py
Labels: bug

#157 Doc/document statepoint behavior
  signac/contrib/job.py
  signac/core/jsondict.py
Labels: documentation
