Repository glotzerlab/signac, pull requests merged in 2020-01, with the labels that each got.

#266 Make tests pass on Windows and test Windows on CI
  .circleci/config.yml
  changelog.txt
  requirements-benchmark.txt
  requirements-dev.txt
  signac/__init__.py
  signac/__main__.py
  signac/contrib/__init__.py
  signac/contrib/filterparse.py
  signac/contrib/import_export.py
  signac/contrib/job.py
  signac/contrib/project.py
  signac/contrib/utility.py
  signac/core/dict_manager.py
  signac/core/h5store.py
  signac/core/json.py
  tests/test_collection.py
  tests/test_h5store.py
  tests/test_job.py
  tests/test_project.py
  tests/test_shell.py
Labels: bug, enhancement

#270 Fix/tarfile import long sp
  signac/contrib/import_export.py
  tests/test_project.py
Labels: bug

#269 Fix usage of _convert_to_dict to avoid modifying nesting SyncedDict objects when calling items or values
  changelog.txt
  signac/core/synceddict.py
  tests/test_synced_attrdict.py
Labels: bug

#275 Changed testing framework (Pytest)
  .circleci/config.yml
  README.md
  changelog.txt
  doc/support.rst
  requirements-dev.txt
  tests/test_buffered_mode.py
  tests/test_collection.py
  tests/test_db.py
  tests/test_diff.py
  tests/test_find_command_line_interface.py
  tests/test_h5store.py
  tests/test_h5store_manager.py
  tests/test_indexing.py
  tests/test_job.py
  tests/test_jsondict.py
  tests/test_numpy_integration.py
  tests/test_pandas_integration.py
  tests/test_project.py
  tests/test_shell.py
  tests/test_sync.py
  tests/test_synced_attrdict.py
  tests/test_temporary_project.py
  tests/test_versioning.py
Labels: enhancement
