Repository glotzerlab/signac, pull requests merged in 2020-07, with the labels that each got.

#340 Drop Support for Python 3.5
  .circleci/config.yml
  README.md
  changelog.txt
  doc/installation.rst
  setup.py
  signac/contrib/collection.py
  signac/contrib/import_export.py
  tests/conda_create_config_host_test_env.sh
  tests/conda_create_test_env.sh
Labels: GSoC, enhancement

#343 Apply NumPy docstyle to remaining files in "signac" root.
  setup.cfg
  signac/__init__.py
  signac/__main__.py
  signac/diff.py
  signac/sync.py
  signac/syncutil.py
  signac/testing.py
  signac/version.py
Labels: doc-style

#342 Refactor docs to use inclusive language.
  CONTRIBUTING.md
  changelog.txt
  doc/api.rst
  signac/__init__.py
  signac/__main__.py
  signac/contrib/__init__.py
  signac/contrib/indexing.py
  signac/contrib/project.py
  tests/test_indexing.py
Labels: documentation

#356 Apply fixes from minirst.
  signac/contrib/collection.py
  signac/contrib/filterparse.py
  signac/contrib/import_export.py
  signac/contrib/linked_view.py
  signac/contrib/project.py
  signac/contrib/utility.py
Labels: doc-style

#354 Enforce pydocstyle in core, common, contrib.
  setup.cfg
  signac/common/.gitignore
  signac/common/__init__.py
  signac/common/config.py
  signac/common/validate.py
  signac/contrib/__init__.py
  signac/contrib/collection.py
  signac/contrib/job.py
  signac/contrib/linked_view.py
  signac/contrib/migration/__init__.py
  signac/contrib/migration/v0_to_v1.py
  signac/core/__init__.py
  signac/core/jsondict.py
Labels: doc-style

#357 NumPy docstring style
  doc/conf.py
  setup.cfg
  signac/__init__.py
  signac/__main__.py
  signac/common/.gitignore
  signac/common/__init__.py
  signac/common/config.py
  signac/common/errors.py
  signac/common/validate.py
  signac/contrib/__init__.py
  signac/contrib/collection.py
  signac/contrib/errors.py
  signac/contrib/filterparse.py
  signac/contrib/hashing.py
  signac/contrib/import_export.py
  signac/contrib/job.py
  signac/contrib/linked_view.py
  signac/contrib/migration/__init__.py
  signac/contrib/migration/v0_to_v1.py
  signac/contrib/project.py
  signac/contrib/schema.py
  signac/contrib/utility.py
  signac/core/__init__.py
  signac/core/attrdict.py
  signac/core/dict_manager.py
  signac/core/errors.py
  signac/core/h5store.py
  signac/core/json.py
  signac/core/jsondict.py
  signac/core/synceddict.py
  signac/core/utility.py
  signac/diff.py
  signac/errors.py
  signac/sync.py
  signac/syncutil.py
  signac/testing.py
  signac/version.py
  signac/warnings.py
Labels: doc-style

#336 Improve Sync Data Structures
  .github/dependabot.yml
  requirements-benchmark.txt
  requirements-dev.txt
  setup.cfg
  signac/core/jsoncollection.py
  signac/core/synced_collection.py
  signac/core/synced_list.py
  signac/core/syncedattrdict.py
  tests/test_synced_collection.py
Labels: GSoC
