Repository glotzerlab/signac, pull requests merged in 2020-04, with the labels that each got.

#313 Add typing to signac.core.json.
  .circleci/config.yml
  changelog.txt
  setup.cfg
  signac/common/errors.py
  signac/common/host.py
  signac/contrib/filterparse.py
  signac/contrib/indexing.py
  signac/contrib/project.py
  signac/core/h5store.py
  signac/core/json.py
  signac/errors.py
  signac/syncutil.py
Labels: refactor

#310 Improve Project docstrings.
  signac/contrib/project.py
Labels: documentation

#318 numpydoc style(signac/contrib/schema.py)
  doc/conf.py
  setup.cfg
  signac/contrib/import_export.py
  signac/contrib/project.py
  signac/contrib/schema.py
Labels: documentation

#325 Show a palette emoji 🎨 in signac shell's version info.
  signac/__main__.py
Labels: enhancement
