Repository glotzerlab/signac, pull requests merged in 2020-12, with the labels that each got.

#433 Raise DestinationExistsError from EEXIST.
  signac/contrib/import_export.py
  signac/contrib/job.py
Labels: bug

#429 Optimize _dfs_convert by exiting early for common types.
  changelog.txt
  signac/core/synceddict.py
Labels: enhancement

#363 Added buffering to SyncedCollection
  signac/core/buffered_synced_collection.py
  signac/core/caching.py
  signac/core/collection_json.py
  signac/core/errors.py
  signac/core/file_buffered_synced_collection.py
  signac/core/synced_collection.py
  signac/core/syncedattrdict.py
  tests/test_buffered_synced_collection.py
  tests/test_synced_collection.py
Labels: GSoC

#450 Minor style changes.
  .circleci/config.yml
  benchmark.py
  signac/__main__.py
  signac/contrib/import_export.py
  signac/contrib/job.py
  signac/contrib/linked_view.py
  signac/contrib/project.py
  signac/contrib/schema.py
  signac/diff.py
Labels: refactor

#442 Optimize job __hash__ and __eq__ checks.
  signac/contrib/job.py
  tests/test_project.py
Labels: enhancement

#239 Lazy statepoint loading
  benchmark.py
  changelog.txt
  signac/contrib/job.py
  signac/contrib/project.py
  tests/test_project.py
Labels: enhancement
