Repository glotzerlab/signac, pull requests merged in 2020-09, with the labels that each got.

#376 Fix/dot format bug
  signac/__main__.py
  tests/test_sync.py
Labels: bug

#378 Added validation layer to SyncedCollection
  setup.cfg
  signac/core/collection_json.py
  signac/core/collection_mongodb.py
  signac/core/collection_redis.py
  signac/core/collection_zarr.py
  signac/core/synced_collection.py
  signac/core/synced_list.py
  signac/core/syncedattrdict.py
  signac/core/validators.py
  tests/test_synced_collection.py
  tests/test_validators.py
Labels: GSoC

#379 Remove dependency on pytest-subtests.
  changelog.txt
  requirements-dev.txt
  tests/test_project.py
Labels: dependencies, enhancement
