Repository glotzerlab/signac, pull requests merged in 2020-03, with the labels that each got.

#302 Fix import and call related to 'configob.verify'.
  changelog.txt
  signac/__main__.py
  signac/common/configobj/__init__.py
Labels: bug

#300 Added tests and coverage for CLI
  .circleci/config.yml
  requirements-dev.txt
  setup.cfg
  tests/test_shell.py
Labels: Click

#294 Add Doc Linting to CI
  .circleci/config.yml
  contributors.yaml
  requirements-dev.txt
  setup.cfg
  signac/core/jsondict.py
Labels: documentation, enhancement

#307 Add xfail to multithreaded H5Store test that fails randomly.
  tests/test_h5store.py
Labels: bug
