Repository glotzerlab/signac, pull requests merged in 2021-01, with the labels that each got.

#443 Optimize H5Store init.
  changelog.txt
  signac/core/h5store.py
Labels: enhancement

#455 Handle non-Job objects in Job equality check.
  changelog.txt
  signac/contrib/job.py
  tests/test_job.py
Labels: bug

#451 Optimization: job/project initialization.
  changelog.txt
  signac/contrib/job.py
  signac/contrib/migration/__init__.py
  signac/contrib/project.py
Labels: enhancement, refactor

#467 Fix: don't delete invalid statepoints
  signac/contrib/job.py
  tests/test_job.py
  tests/test_project.py
Labels: bug

#474 Add oldest & minimal CI configurations.
  .circleci/config.yml
  changelog.txt
  requirements-benchmark.txt
  requirements/requirements-benchmark.txt
  requirements/requirements-precommit.txt
  requirements/requirements-test-optional.txt
  requirements/requirements-test.txt
Labels: dependencies

#477 Add support for zero-dimensional numpy arrays.
  changelog.txt
  signac/core/synceddict.py
  tests/test_numpy_integration.py
Labels: bug

#444 doc/bettter document update and reset statepoint
  signac/contrib/collection.py
  signac/contrib/import_export.py
  signac/contrib/job.py
  signac/contrib/project.py
  signac/errors.py
  signac/sync.py
Labels: documentation

#475 adding documentation for JobsCursor api
  doc/api.rst
  signac/contrib/project.py
Labels: documentation
