Repository glotzerlab/signac, pull requests merged in 2022-03, with the labels that each got.

#693 Remove support for custom job subclass
  changelog.txt
  signac/contrib/import_export.py
  signac/contrib/project.py
  tests/test_project.py
Labels: enhancement

#710 Catch KeyError as another possible failure of multithreading
  tests/test_synced_collections/synced_collection_test.py
Labels: bug

#705 Run tests in parallel with pytest-xdist.
  .circleci/ci-oldest-reqs.txt
  .circleci/config.yml
  changelog.txt
  requirements/requirements-test.txt
Labels: enhancement

#711 Move discovery to separate functions.
  signac/__main__.py
  signac/common/config.py
  signac/common/validate.py
  signac/contrib/project.py
Labels: enhancement

#683 Remove Collection
  .circleci/config.yml
  benchmark.py
  benchmarks/benchmarks.py
  changelog.txt
  doc/api.rst
  requirements/requirements-benchmark.txt
  signac/__init__.py
  signac/contrib/__init__.py
  signac/contrib/_searchindexer.py
  signac/contrib/collection.py
  signac/contrib/schema.py
  tests/test_collection.py
Labels: enhancement, blocked, refactor, requires-1.x-deprecation

#718 Replace deprecation decorator with vendored deprecation decorator for FutureWarnings
  .circleci/ci-oldest-reqs.txt
  changelog.txt
  requirements.txt
  setup.py
  signac/cite.py
  signac/common/config.py
  signac/common/connection.py
  signac/common/crypt.py
  signac/common/host.py
  signac/contrib/filesystems.py
  signac/contrib/indexing.py
  signac/contrib/job.py
  signac/contrib/mpipool.py
  signac/contrib/utility.py
  signac/core/json.py
  signac/core/jsondict.py
  signac/core/synceddict.py
  signac/core/utility.py
  signac/db/database.py
  signac/syncutil.py
  tests/test_buffered_mode.py
  tests/test_db.py
  tests/test_indexing.py
Labels: enhancement

#717 Replace _id with id_
  changelog.txt
  signac/__main__.py
  signac/contrib/job.py
  signac/contrib/project.py
  tests/test_job.py
Labels: refactor
