Repository glotzerlab/signac, pull requests merged in 2022-11, with the labels that each got.

#848 Stop filtering out warnings.
  setup.cfg
Labels: enhancement

#847 Remove deprecated config APIs.
  changelog.txt
  signac/common/config.py
Labels: refactor

#853 Remove common.validate
  changelog.txt
  signac/common/config.py
  signac/common/validate.py
  signac/contrib/migration/v0_to_v1.py
  signac/contrib/migration/v1_to_v2.py
  signac/core/dict_manager.py
Labels: refactor

#851 Remove old tests
  tests/host_config_test.sh
  tests/host_config_tests.sh
  tests/test_jsondict.py
Labels: refactor

#846 Remove unnecessary _add_prefix call and simplify as much as possible.
  signac/contrib/filterparse.py
  signac/contrib/project.py
Labels: refactor

#858 Make _DictManager private.
  changelog.txt
  signac/core/dict_manager.py
  signac/core/h5store.py
Labels: refactor

#859 Miscellaneous TODO items
  setup.cfg
  signac/__main__.py
  tests/test_searchindexer.py
Labels: refactor

#856 Update v2 migration logic.
  signac/contrib/migration/v1_to_v2.py
  signac/contrib/project.py
  signac/contrib/utility.py
Labels: bug

#857 Clean up test files
  tests/test_job.py
  tests/test_project.py
Labels: refactor
