Repository glotzerlab/signac, pull requests merged in 2022-01, with the labels that each got.

#656 Revise CLI docs.
  doc/cli-help.txt
  doc/cli.rst
  doc/index.rst
Labels: documentation

#665 Fix typo in groupby docstring.
  signac/contrib/project.py
Labels: bug, documentation

#654 Migrate using project directories instead of project instances
  changelog.txt
  signac/__main__.py
  signac/contrib/migration/__init__.py
  signac/contrib/migration/v0_to_v1.py
  signac/contrib/project.py
  tests/test_project.py
Labels: refactor
