Repository glotzerlab/signac, pull requests merged in 2022-02, with the labels that each got.

#676 Improve test coverage of Collection class's find methods.
  changelog.txt
  signac/contrib/collection.py
  tests/test_collection.py
Labels: bug

#678 Initial migration to schema version 2 including config rename
  signac/__main__.py
  signac/common/config.py
  signac/contrib/migration/__init__.py
  signac/contrib/migration/v1_to_v2.py
  signac/contrib/project.py
  signac/version.py
  tests/test_project.py
  tests/test_shell.py
Labels: refactor

#682 Split test for signac config verify.
  tests/test_shell.py
Labels: enhancement

#667 Replace Collection with lightweight _SearchIndexer.
  signac/contrib/_index.py
  signac/contrib/import_export.py
  signac/contrib/project.py
  signac/contrib/schema.py
  tests/test_collection.py
  tests/test_project.py
  tests/test_searchindexer.py
Labels: enhancement, refactor

#691 Use FutureWarning instead of DeprecationWarning in project.py
  changelog.txt
  signac/contrib/project.py
Labels: enhancement
